added the print function along with ctrl-s and ctrl-o
browserpad/browserpad pull request #51
Opened 2022-04-01 10:40 UTC by SenadAlagic

Hey there. I decided to try and help you with the browserpad project because I myself use it. I added the "print" functionality along with ctrl+s as "Save" (download rather) and ctrl+o as "Open". Hope you're satisfied

2022-05-08 20:07 UTC, waldyrious requested changes
Thanks so much for the contribution, @SenadAlagic! Apologies for the delay in the response.

It's great that you enabled GitHub Pages in your repo, so I can test the changes directly in https://senadalagic.github.io/browserpad/! They seem to work well, and I would like to merge this PR, but I'd appreciate it if you made the changes I requested in the inline comments. Thanks again!

2022-05-08 20:07 UTC, waldyrious commented on index.xhtml
> +    //it into proper functions and make it more readable. I wont change the actual code itself
This would be great, but I'd prefer it in a separate PR. And please remove this comment from this PR's code :)

2022-05-08 20:07 UTC, waldyrious commented on index.xhtml
> +      //console.log(e.keyCode);
This line should be removed :)

2022-05-08 20:07 UTC, waldyrious commented on index.xhtml
> +    //ctrl-s ctrl-o
```suggestion
    // keyboard shortcuts for the save and load functions (`Ctrl+S`, `Ctrl+O`)
```

2022-05-09 14:28 UTC, SenadAlagic commented
Hi there!
I hope I understood you correctly and made the corresponding changes. Thank you for your input.

2022-05-09 20:59 UTC, waldyrious commented on index.xhtml
> +          console.log("ctrl+s");
Do you think it is important to leave these logs here? Or was this for debugging while implementing the functionality?

2022-05-09 20:59 UTC, waldyrious approved these changes

2022-05-12 21:17 UTC, merged

2022-05-12 21:19 UTC, waldyrious commented
Thank you again for the contribution, @SenadAlagic. You're the first contributor to have  changes merged into the project! :tada: :tada:

2022-05-12 21:39 UTC, SenadAlagic commented
Glad to help! I use the website all the time so I'm happy to. Will commit some more soon!